<?php
// Generated by ZF2's ./bin/classmap_generator.php @ Sun, 15 Jan 2012 19:46:42 -0700
return array(
    'ZfcUserDoctrineORM\Module'                            => __DIR__ . '/Module.php',
    'ZfcUserDoctrineORM\Event\ResolveTargetEntityListener' => __DIR__ . '/src/ZfcUserDoctrineORM/Event/ResolveTargetEntityListener.php',
    'ZfcUserDoctrineORM\Mapper\UserMetaDoctrine'           => __DIR__ . '/src/ZfcUserDoctrineORM/Mapper/UserMetaDoctrine.php',
    'ZfcUserDoctrineORM\Mapper\UserDoctrine'               => __DIR__ . '/src/ZfcUserDoctrineORM/Mapper/UserDoctrine.php',
    'ZfcUserDoctrineORM\Entity\UserMappedSuperClass'       => __DIR__ . '/src/ZfcUserDoctrineORM/Entity/UserMappedSuperClass.php',
    'ZfcUserDoctrineORM\Entity\UserMetaMappedSuperClass'   => __DIR__ . '/src/ZfcUserDoctrineORM/Entity/UserMetaMappedSuperClass.php',
    'ZfcUserDoctrineORM\Entity\UserMeta'                   => __DIR__ . '/src/ZfcUserDoctrineORM/Entity/UserMeta.php',
    'ZfcUserDoctrineORM\Entity\User'                       => __DIR__ . '/src/ZfcUserDoctrineORM/Entity/User.php',
);